### PR TITLE
selecting a variable fires an app event

### PR DESCRIPTION
**Pull request by cgalvarino**
See inline FIXME's in case I am hacking this to death.
@lukecampbell

### CODE REVIEW

**Comment by cgalvarino** [comment]
@lukecampbell 

image

I'd like to use a fancier date picker, but I don't know the rules for importing something like https://bootstrap-datepicker.readthedocs.org/en/latest/.

Are we going to allow > 1 param to be plotted at once?

I think it would make most sense to put station messages in the little station metadata panel.

**Comment by lukecampbell** [comment]
Absolutely, I used this on OOI. We just add it to the bower packages and update the grunt file.

https://github.com/asascience-open/ooi-ui/blob/master/bower.json#L27
https://github.com/asascience-open/ooi-ui/blob/master/Gruntfile.js#L273

**Comment by lukecampbell** [comment]
More than one param will be plotted only for the plotting section of the page for now. We can probably add multi-parameter plotting to the station page after we knock out the basic functionality.

**Comment by cgalvarino** [comment]
Luffly.  I think time is a bit overkill, but so be it.

image

**Comment by lukecampbell** [comment]
I like it

**Pull request merged**
