### PR TITLE
Some styling and data fixes

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
screen shot 2015-03-20 at 4 50 58 pm

**Comment by cgalvarino** [comment]
@lukecampbell Boss, I'm not a big fan of this little icon.  Mind if I try and tweak this a bit?  And the lat,lon position went poof.  Any particular reason it went AWOL?

ico

**Comment by lukecampbell** [comment]
Which icon? and the lat and lon did go missing, my bad. It should be somewhere unobtrusive.

**Comment by cgalvarino** [comment]
How about this?  Totally out of the box, but worth a shot.

I HATE logos (I didn't mean icons).  In my mind this is bit but unobtrusive.

logo

If you like this, I would carry this over into the map popup somehow.

**Comment by cgalvarino** [comment]
Teensy bit lighter.

logo

**Pull request merged**
